/**
 * Build a single Ren'Py source string from a project's structured data.
 *
 * Inputs:
 *   - `scenes`     scene-kind nodes ordered as they should appear in the file
 *                  (caller decides ordering, usually a depth-first tree walk)
 *   - `characters` Cast members. Only those with `rpy_var` set become `define`s
 *
 * Output is a self-contained, compilable `.rpy` snippet that includes:
 *   - a small header with the project name and a generated-by note
 *   - one `define rpy_var = Character("Display Name", color="#xxx")` per
 *     linked character
 *   - one `label rpy_label_or_slugified_title:` block per scene, followed by
 *     its serialized body
 *
 * Scenes without a `rpy_label` are still exported — we slugify the title to
 * produce a stable identifier. Scenes without `rpy_blocks` are skipped to
 * avoid emitting empty labels.
 */
import { serializeRpyScript } from "./scriptSerializer";
import type { RpyBlocks } from "./blocks";

export interface ExportScene {
  id: string;
  title: string;
  /** Project-unique label. Falls back to slugified title if null. */
  rpy_label: string | null;
  rpy_blocks: RpyBlocks | null;
}

export interface ExportCharacter {
  name: string;
  rpy_var: string;
  color: string;
}

export interface ExportInput {
  projectTitle: string;
  scenes: ExportScene[];
  characters: ExportCharacter[];
}

export interface ExportResult {
  text: string;
  /** Filename suggestion (slugified project title + `.rpy`). */
  filename: string;
  /** How many scene entries actually wrote a label block. */
  sceneCount: number;
  /** How many characters got `define`-d (those with rpy_var). */
  characterCount: number;
  /** Labels that ended up duplicated after slugification — caller may surface. */
  warnings: string[];
}

const NL = "\n";

function slugifyLabel(s: string): string {
  const slug = s
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 60);
  return slug || "scene";
}

function quoteString(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

export function buildRenpyProjectFile(input: ExportInput): ExportResult {
  const out: string[] = [];
  const warnings: string[] = [];

  // ── Header ────────────────────────────────────────────────────────────
  out.push(`# ${input.projectTitle}`);
  out.push(`# Generated by RenHub. Edit in RenHub, not here.`);
  out.push("");

  // ── Character defines ────────────────────────────────────────────────
  const linkedChars = input.characters.filter((c) => c.rpy_var.trim());
  if (linkedChars.length > 0) {
    out.push(`# ── Characters ────────────────────────────────────────`);
    for (const c of linkedChars) {
      const args: string[] = [quoteString(c.name)];
      if (c.color) args.push(`color=${quoteString(c.color)}`);
      out.push(`define ${c.rpy_var} = Character(${args.join(", ")})`);
    }
    out.push("");
  }

  // ── Scenes ────────────────────────────────────────────────────────────
  out.push(`# ── Script ──────────────────────────────────────────`);
  out.push("");

  const usedLabels = new Set<string>();
  let sceneCount = 0;

  for (const scene of input.scenes) {
    const blocks = scene.rpy_blocks ?? [];
    if (blocks.length === 0) continue;

    let label = scene.rpy_label?.trim() || slugifyLabel(scene.title);
    if (usedLabels.has(label)) {
      // Append a numeric suffix to avoid Ren'Py compile error.
      let n = 2;
      while (usedLabels.has(`${label}_${n}`)) n++;
      const next = `${label}_${n}`;
      warnings.push(
        `Duplicate label "${label}" — exported as "${next}" instead.`,
      );
      label = next;
    }
    usedLabels.add(label);

    out.push(`label ${label}:`);
    // serializeRpyScript writes blocks at their stored depth; scenes inside
    // a label should sit at depth 1, so we re-stamp depths before handing
    // them to the serializer to keep emit consistent regardless of the
    // editor's internal depth tracking.
    const rebased = blocks.map((b) => ({ ...b, depth: Math.max(1, b.depth) }));
    const body = serializeRpyScript(rebased);
    out.push(body.replace(/\n$/, ""));
    out.push("");

    sceneCount++;
  }

  const text = out.join(NL).replace(/\n{3,}/g, "\n\n");
  const filename = slugifyLabel(input.projectTitle) + ".rpy";

  return {
    text,
    filename,
    sceneCount,
    characterCount: linkedChars.length,
    warnings,
  };
}
